---
title: "DAS10002 -Breed Extracton Demonstration"
author: "Donald Szlosek"
date: "October 18th, 2018"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
---

```{r message=FALSE, echo=FALSE}

rm(list=ls())

packages = c('rmarkdown', 'plyr', 'dplyr','magick','tesseract','here')

package.check <- lapply(packages, FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
        install.packages(x, dependencies = TRUE)
        library(x, character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)
    }
})



```


```{r Example 1: Casella & Berger}

# import image
casella <- magick::image_read(here::here("2. Data", "casella_berger.png"))

casella

# OCR on the object
casella_ocr <- tesseract::ocr(casella)


# print out un-formatted
casella_ocr


# print out formatted
cat(casella_ocr)

```



```{r Example 2: Skewed Text}
# import image
skewed <- magick::image_read(here::here("2. Data", "skewed_text.png"))

skewed

# OCR on the object
skewed_ocr <- tesseract::ocr(skewed)


# print out un-formatted
skewed_ocr


# print out formatted
cat(skewed_ocr)


```













```{r Example 3}

breed <- magick::image_read_pdf(here::here("2. Data", "single_page.pdf"), pages = 1)

breed

```


```{r image analysis no preprocessing}

breed_ocr_raw <-  ocr(breed)
cat(breed_ocr_raw)

```

```{r image processing - }
breed_charcoal <- magick::image_charcoal(breed, radius = 1, sigma = 0.5)

breed_charcoal

breed_ocr_char <- ocr(breed_charcoal)
cat(breed_ocr_char)
```

```{r image preprocessing}
breed_flat <- magick::image_flatten(breed, 'Modulate')

breed_flat

breed_ocr_flat <- ocr(breed_flat)
cat(breed_ocr_flat)
```


```{r image preprocessing}

library(magick)

library(tesseract)

page_process <- magick::image_flatten(breed, 'Modulate') %>% image_crop(.,"600x800")
page_process

text_process <- ocr(page_process)
cat(text_process)

```


```{r image preprocessing - Step 1 Get the dog name}
                                                            # width x height
page_process1 <- image_flatten(breed, 'Modulate') %>% image_crop(.,"1800x100+100+200")
page_process1

text_process1 <- ocr(page_process1)
cat(text_process1)


breed_name <- text_process1 %>% data.frame() %>% dplyr::rename(., "breed" = ".")
```

```{r image preprocessing - Step 2 Get the dog info}
                                                            # width x height
page_process2 <- image_flatten(breed, 'Modulate') %>% image_crop(.,"500x300+100+400")
page_process2

text_process2 <- ocr(page_process2)
cat(text_process2)

breed_info <- text_process2 %>% data.frame() %>% dplyr::rename(., "breed.info" = ".")
```

```{r image preprocessing - Step 3 Get the dog name for 2nd half of page}
                                                            # width x height
page_process3 <- image_flatten(breed, 'Modulate') %>% image_crop(.,"1800x100+100+1450")
page_process3

text_process3 <- ocr(page_process3)
cat(text_process3) 

breed_name2 <- text_process3 %>% data.frame() %>% dplyr::rename(., "breed" = ".")
```

```{r image preprocessing - Step 4 Get the dog info for 2nd half of page}
                                                            # width x height
page_process4 <- image_flatten(breed, 'Modulate') %>% image_crop(.,"500x300+100+1650")
page_process4

text_process4 <- ocr(page_process4)
cat(text_process4)


breed_info2 <- text_process4 %>% data.frame() %>% dplyr::rename(., "breed.info" = ".")
```

```{r data construction}

top_half <- cbind(breed_name,breed_info)

bottom_half <- cbind(breed_name2,breed_info2)

single_page <- rbind(top_half,bottom_half) 


head(single_page)
```



```{r}
library(stringr)
dc1 <- single_page %>% group_by(breed) %>%
                       mutate(height_range = gsub("[()]", "",str_extract_all(breed.info, "\\([^()]+\\)")[[1]][1]),
                              mass_range   = gsub("[()]", "",str_extract_all(breed.info, "\\([^()]+\\)")[[1]][2]),
                              origin = substring(breed.info,first= str_locate(breed.info,"Origin")[1])
                              ) %>% ungroup()

library(tidyverse)

dc2 <- dc1 %>% separate(height_range, c("height_min", "height_max")) %>%
               separate(mass_range, c("mass_min","mass_max"))
  
  
remove_words <- function(str, stopwords) {
  x <- unlist(strsplit(str, " "))
  paste(x[!x %in% stopwords], collapse = " ")
}

dc3 <- dc2 %>% rowwise() %>% transmute(breed      =  breed,
                         height_min =  as.numeric(height_min),
                         height_max =  as.numeric(str_extract(height_max, "\\d+")),
                         mass_min   =  as.numeric(mass_min),
                         mass_max   =  as.numeric(str_extract(mass_max, "\\d+")),
                         origin     =  remove_words(origin,"Origin")
                         )

```




```{r}
# import image
test <- magick::image_read('C:\\Users\\donal\\Desktop\\IMG-3421.jpg')

magick::image_flatten()
test
tesser <- tesseract::ocr(test)

cat(tesser)

```

